[project]
name = "vdb-cards-update"
version = "2025.3.15"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "unidecode>=1.3.8",
]

[tool.ruff]
line-length = 100
